package app.modelo;

public enum AreasDeConhecimento {
	GEOGRAFIA, ARTES, BIOLOGIA, EDUCACAO_FISICA, FILOSOFIA, HISTORIA, MATEMATICA, FISICA, QUIMICA, SOCIOLOGIA, LINGUA_PORTUGUESA,
	LITERATURA, LINGUA_INGLESA, LINGUA_ALEMA, LINGUA_FRANCESA
}
